package com.zhongrun.model;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Proxy;

import com.zhongrun.common.model.AbstractModel;

// Generated 2014-1-9 15:33:45 by Hibernate Tools 3.4.0.CR1


/**
 * Adflow generated by hbm2java
 */
@Entity
@Proxy(lazy = true)
@Table(name = "ADFLOW_DAY")
public class AdFlowDay extends AbstractModel implements Cloneable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4575838543749522601L;
	@Id
	@SequenceGenerator(name = "ADFLOW_DAY_PK", allocationSize=1, initialValue=1, sequenceName = "SEQ_ADFLOW_DAY")
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator = "ADFLOW_DAY_PK")
	private Integer id;
	@Column(name="APPID")
	private Integer appId;
	@Column(name="UNPACKNO")
	private String unpackNo;
	@Column(name="CHANNELID")
	private String channelId;
	@Column(name="ADID")
	private Integer adId;
	@Column(name="ADPUTID")
	private Integer adputId;
	@Column(name="ADBOXID")
	private Integer adBoxId;
	@Column(name="CYCLEID")
	private Integer cycleId;
	@Column(name="PROVINCE")
	private String province;
	@Column(name="CITY")
	private String city;
	@Column(name="NETWORK")
	private String network;
	@Column(name="SPTYPE")
	private Integer sptype;
	@Column(name="DATETIME")
	private Integer dateTime;
	@Column(name="CREATETIME")
	private Timestamp createTime;
	@Column(name="EFFICTIVECLICKTIMES")
	private Integer efftictiveClickTimes;//有效点击
	@Column(name="CLICKTIMES")
	private Integer clickTimes;//总点击
	@Column(name="EFFICTIVESHOWTIMES")
	private Integer efftictiveShowTimes;//有效显示
	@Column(name="SHOWTIMES")
	private Integer showTimes;//总显示
	@Column(name="EFFICTIVEDOWNLOADTIMES")
	private Integer efftictiveDownloadTimes;//有效下载完成
	@Column(name="DOWNLOADTIMES")
	private Integer downloadTimes;//总下载完成
	@Column(name="EFFICTIVEINSTALLTIMES")
	private Integer efftictiveInstallTimes;//有效安装
	@Column(name="INSTALLTIMES")
	private Integer installTimes;//总安装
	@Column(name="EFFICTIVECLICK2DOWNLOAD")
	private Integer efftictiveClick2Download;//有效下载
	@Column(name="CLICK2DOWNLOAD")
	private Integer click2Download;//总下载
	
	@Transient
	private String adName;
	@Transient
	private String adBoxName;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAppId() {
		return appId;
	}

	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	public String getUnpackNo() {
		return unpackNo;
	}

	public void setUnpackNo(String unpackNo) {
		this.unpackNo = unpackNo;
	}

	public String getChannelId() {
		return channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	public Integer getAdId() {
		return adId;
	}

	public void setAdId(Integer adId) {
		this.adId = adId;
	}

	public Integer getAdputId() {
		return adputId;
	}

	public void setAdputId(Integer adputId) {
		this.adputId = adputId;
	}

	public Integer getAdBoxId() {
		return adBoxId;
	}

	public void setAdBoxId(Integer adBoxId) {
		this.adBoxId = adBoxId;
	}

	public Integer getCycleId() {
		return cycleId;
	}

	public void setCycleId(Integer cycleId) {
		this.cycleId = cycleId;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getNetwork() {
		return network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	public Integer getSptype() {
		return sptype;
	}

	public void setSptype(Integer sptype) {
		this.sptype = sptype;
	}

	public Integer getDateTime() {
		return dateTime;
	}

	public void setDateTime(Integer dateTime) {
		this.dateTime = dateTime;
	}

	public Timestamp getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Integer getEfftictiveClickTimes() {
		return efftictiveClickTimes;
	}

	public void setEfftictiveClickTimes(Integer efftictiveClickTimes) {
		this.efftictiveClickTimes = efftictiveClickTimes;
	}

	public Integer getClickTimes() {
		return clickTimes;
	}

	public void setClickTimes(Integer clickTimes) {
		this.clickTimes = clickTimes;
	}

	public Integer getEfftictiveShowTimes() {
		return efftictiveShowTimes;
	}

	public void setEfftictiveShowTimes(Integer efftictiveShowTimes) {
		this.efftictiveShowTimes = efftictiveShowTimes;
	}

	public Integer getShowTimes() {
		return showTimes;
	}

	public void setShowTimes(Integer showTimes) {
		this.showTimes = showTimes;
	}

	public Integer getEfftictiveDownloadTimes() {
		return efftictiveDownloadTimes;
	}

	public void setEfftictiveDownloadTimes(Integer efftictiveDownloadTimes) {
		this.efftictiveDownloadTimes = efftictiveDownloadTimes;
	}

	public Integer getDownloadTimes() {
		return downloadTimes;
	}

	public void setDownloadTimes(Integer downloadTimes) {
		this.downloadTimes = downloadTimes;
	}

	public Integer getEfftictiveInstallTimes() {
		return efftictiveInstallTimes;
	}

	public void setEfftictiveInstallTimes(Integer efftictiveInstallTimes) {
		this.efftictiveInstallTimes = efftictiveInstallTimes;
	}

	public Integer getInstallTimes() {
		return installTimes;
	}

	public void setInstallTimes(Integer installTimes) {
		this.installTimes = installTimes;
	}

	public String getAdName() {
		return adName;
	}

	public void setAdName(String adName) {
		this.adName = adName;
	}

	public String getAdBoxName() {
		return adBoxName;
	}

	public void setAdBoxName(String adBoxName) {
		this.adBoxName = adBoxName;
	}
	
	public String getChangeRate(){
		if(null != this.efftictiveShowTimes && this.efftictiveShowTimes > 0){
			double rate = this.efftictiveDownloadTimes*100/this.efftictiveShowTimes;
			return String .format("%.2f", rate)+"%";
		}
		return "";
	}
	
	public String getDownloadSuccessRate(){
		if(null != this.downloadTimes && this.downloadTimes > 0){			
			double rate = this.efftictiveDownloadTimes*100/this.downloadTimes;
			return String .format("%.2f", rate)+"%";
		}
		return "";
	}
	
	/**
	 * @return the efftictiveClick2Download
	 */
	public Integer getEfftictiveClick2Download() {
		return efftictiveClick2Download;
	}

	/**
	 * @param efftictiveClick2Download the efftictiveClick2Download to set
	 */
	public void setEfftictiveClick2Download(Integer efftictiveClick2Download) {
		this.efftictiveClick2Download = efftictiveClick2Download;
	}

	/**
	 * @return the click2Download
	 */
	public Integer getClick2Download() {
		return click2Download;
	}

	/**
	 * @param click2Download the click2Download to set
	 */
	public void setClick2Download(Integer click2Download) {
		this.click2Download = click2Download;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
}
